# permissions for end users to edit packagerevisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: packagerevision-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: porchapi
    app.kubernetes.io/part-of: porchapi
    app.kubernetes.io/managed-by: kustomize
  name: packagerevision-editor-role
rules:
- apiGroups:
  - porch.s3wong.io
  resources:
  - packagerevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - porch.s3wong.io
  resources:
  - packagerevisions/status
  verbs:
  - get
