---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - porch.s3wong.io
  resources:
  - packagerevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - porch.s3wong.io
  resources:
  - packagerevisions/finalizers
  verbs:
  - update
- apiGroups:
  - porch.s3wong.io
  resources:
  - packagerevisions/status
  verbs:
  - get
  - patch
  - update
